version: 2.1

orbs:
  gh: circleci/github-cli@2.7.0

jobs:
  build-linux-debug:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Get Dependancies and Setup"
          command: |
            sudo apt-get update
            sudo apt-get install gcc-14 g++-14 ninja-build
            mkdir /tmp/linux-artifacts
      - run:
          name: "Build executable"
          command: |
            cmake -Bbuild -H. -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_CXX_COMPILER=g++-14 -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -G Ninja
            cd build
            ninja --verbose
            cd ..
            mv bin/lagrange-ng bin/lagrange-ng-linux-debug
            mv bin/lagrange-test bin/lagrange-test-linux-debug
      - persist_to_workspace:
          root: .
          paths:
            - bin/lagrange-ng-linux-debug
            - bin/lagrange-test-linux-debug
  build-linux-static:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Get Dependancies and Setup"
          command: |
            sudo apt-get update
            sudo apt-get install gcc-14 g++-14 ninja-build
            mkdir /tmp/linux-artifacts
      - run:
          name: "Build executable"
          command: |
            cmake -Bbuild -H. -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_CXX_COMPILER=g++-14 -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY_STATIC=ON -DDYNAMIC_ARCH=ON -G Ninja
            cd build
            ninja --verbose
            cd ..
            mv bin/lagrange-ng bin/lagrange-ng-linux-static
      - persist_to_workspace:
          root: .
          paths:
            - bin/lagrange-ng-linux-static
  run-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - attach_workspace:
          at: artifacts
      - run:
          name: "Run linux tests"
          command: |
            ./artifacts/bin/lagrange-test-linux-debug

  upload-release:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - gh/install
      - attach_workspace:
          at: artifacts
      - run:
          name: "Upload Release"
          command: |
            gh release upload << pipeline.git.tag >> ./artifacts/bin/lagrange-ng-linux-static
            # gh release upload << pipeline.git.tag >> ./linux-artifacts/lagrange-ng#lagrange-ng-macos-static

workflows:
  build-workflow: 
    jobs:
      - build-linux-debug
      - run-tests:
          requires:
            - build-linux-debug

      - build-linux-static:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - gh/release:
          tag: "<< pipeline.git.tag >>"
          title: "Release-test-ci-3"
          context:
            - GITHUB_TOKEN
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - upload-release:
          context:
            - GITHUB_TOKEN
          requires:
            - gh/release
            - build-linux-static
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
