# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  gh: circleci/github-cli@2.7.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-linux-static:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Get Dependancies and Setup"
          command: |
            sudo apt-get update
            sudo apt-get install gcc-14 g++-14 ninja-build
            mkdir linux-artifacts
      - run:
          name: "Build executable"
          command: |
            cmake -Bbuild -H. -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_CXX_COMPILER=g++-14 -DBUILD_TESTS=ON -G Ninja
            cd build
            ninja --verbose
      - persist_to_workspace:
          root: linux-artifacts
          paths:
            - bin/lagrange-ng
            - bin/lagrange-test
  build-mac-static:
    macos:
      xcode: 16.4.0
    resource_class: m4pro.medium
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run:
          name: "Install Ninja"
          command: |
            brew install ninja
            mkdir macos-artifacts
      - run:
          name: "Build Executable"
          command: |
            cmake -Bbuild -H. -DBUILD_TESTS=ON -G Ninja
            cd build
            ninja --verbose
      - persist_to_workspace:
          root: macos-artifacts
          paths:
            - bin/lagrange-ng
            - bin/lagrange-test
  run-tests:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run linux tests"
          command: |
            cd bin
            ./linux-artifacts/lagrange-test

  run-tests-macos:
    macos:
      xcode: 16.4.0
    resource_class: m4pro.medium
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run linux tests"
          command: |
            cd bin
            ./macos-artifacts/lagrange-test

  upload-release:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - gh/install
      - run:
          name: "Upload Release"
          command: |
            gh release upload << pipeline.git.tag >> ./linux-artifacts/lagrange-ng#lagrange-ng-linux-static
            # gh release upload << pipeline.git.tag >> ./linux-artifacts/lagrange-ng#lagrange-ng-macos-static



# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - build-linux-static:
          filters:
            tags:
              only: /^v.*/
      - run-tests:
          requires:
            - build-linux-static
          filters:
            tags:
              only: /^v.*/
      - gh/release:
          tag: "<< pipeline.git.tag >>"
          title: "Release-test-ci-3"
          context:
            - GITHUB_TOKEN
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - upload-release:
          context:
            - GITHUB_TOKEN
          requires:
            - gh/release
            - run-tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
