name: Build and run tests 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            c_compiler: gcc-14
            cpp_compiler: g++-14
            build_type: Debug
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Debug

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "bin-output-dir=${{ github.workspace }}/bin" >> "$GITHUB_OUTPUT"

    - name: Install Deps
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get install libopenblas-dev liblapacke-dev

    - name: Install Deps
      if: matrix.os == 'macos-latest'
      shell: bash
      run: |
        brew install llvm openblas nlopt libomp

    - name: Configure CMake
      if: matrix.os != 'macos-latest'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBUILD_TESTS=ON
        -S ${{ github.workspace }}

    - name: Configure CMake
      if: matrix.os == 'macos-latest'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@18)/bin/${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=$(brew --prefix llvm@18)/bin/${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DOpenBLAS_INCLUDE_DIRS=$(brew --prefix openblas)/include
        -DOpenBLAS_LIBRARY_DIRS=$(brew --prefix openblas)/lib
        -DBUILD_TESTS=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Run Tests
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -t test
